- pyproject.toml
> Revert "license update"

- .github/workflows/linter.yml
- ultraplot/axes/base.py
- ultraplot/axes/plot.py
- ultraplot/config.py
- ultraplot/demos.py
- ultraplot/figure.py
- ultraplot/internals/inputs.py
- ultraplot/internals/rcsetup.py
- ultraplot/tests/test_1dplots.py
We promote black, we should add black as part of the workflow. Note currently the repo is not black compatible!
> added linter workflow

- ultraplot/axes/plot.py
- ultraplot/constructor.py
I merge too quickly with the other PR -- these address the points raided by  @beckermr
> Cycling hotfix2

- .github/workflows/build-docs.yml
- docs/environment.yml
- environment-dev.yml
As it says on the tin.
I have moved the theme under the organization. I have fixed some of the python compatibility there.
> Move theme under organization

- .readthedocs.yml
Read the docs are failing. Needed to add install to ensure the imports work in the doctests
> Readthedocs fix

- pyproject.toml
This PR is the correct fix for custom classifiers.
> fix: remove custom classifier for MPL

- ultraplot/tests/test_1dplots.py
Think the test introduced in #76 didn't use the seed fixed in the test causing a potential reproducibility issue in #78
> use seed for reproducibility

- docs/conf.py
> rm warnings when downloading data inside env

- .readthedocs.yml
- pyproject.toml
> prod: add me to maintainers

- .github/workflows/build-ultraplot.yml
- .github/workflows/main.yml
- README.rst
- codecov.yml
- environment.yml
- ultraplot/__init__.py
This PR enables test coverage measurements with codecov.
> feat: enable test coverage with codecov

- docs/_scripts/fetch_releases.py
There was an erroneous extra line in the formatting. Otherwise it looks great :D
> rm extra == line

- ultraplot/tests/conftest.py
Reducing the verbosity in the stage where the baseline images are compared to enhance which tests are failed.
> reduce verbosity of extension

- docs/conf.py
- docs/projections.py
PR corrects the urls to enable cross referencing docs with sphinx.
> Update intersphinx links

- docs/index.rst
Continuation of #132 where the amount of columns is adjusted per screen size.
> Make it mobile friendly

- README.rst
To draw more people in, we need to show by example. This PR creates a dynamic gallery to show on the main page.
> Add gallery to github page

- ultraplot/internals/fonts.py
- ultraplot/tests/test_fonts.py
First steps into getting coverage towards 80 percent.
> Add unitests for ultraplot.internals.fonts

- ultraplot/config.py
- ultraplot/tests/test_config.py
> Ipy rc kernel reset

- ultraplot/tests/conftest.py
> Capture warning

- ultraplot/tests/test_format.py
TODO: figure out why this is failing on github actions
> tmp turning of test

- ultraplot/tests/conftest.py
Reverts Ultraplot/ultraplot#175
> Revert "Skip missing tests if added in PR"

- ultraplot/axes/base.py
- ultraplot/tests/test_colorbar.py
> Fix colorbar loc

- ultraplot/axes/plot.py
- ultraplot/tests/test_1dplots.py
Partly addresses #191 
Minor change if passes merging directly.
> Fix bar alpha

- ultraplot/tests/test_geographic.py
Very minor refactor -- merging on success.
> make import uplt to be consistent with rest of repo

- ultraplot/axes/plot.py
- ultraplot/tests/test_plot.py
> Avoid getting edges and setting centers for some shaders

- .github/workflows/build-ultraplot.yml
- .github/workflows/main.yml
- environment.yml
- pyproject.toml
- ultraplot/axes/geo.py
- ultraplot/figure.py
> fix: specify import exception type and add typing-extensions to deps

- ultraplot/axes/plot.py
- ultraplot/internals/rcsetup.py
- ultraplot/tests/test_plot.py
> fix cycler setting to 1 when only 1 column is parsed

- docs/projections.py
As it says on the tin. Removed the sharing as it causes some issue with some plots.
> Fix numerous geo docs visuals

- environment.yml
- pyproject.toml
- ultraplot/axes/cartesian.py
> Bump python to 3.13

- ultraplot/axes/plot.py
- ultraplot/tests/test_plot.py
~~- The change in networkx is due to a change on the networkx side.~~
> Fix a few tests

- ultraplot/tests/test_1dplots.py
Until the issue of the decorator is fixed, we replace the layout with one that does not have this issue (and yours truly wrote).
> Replace spring with forceatlas2

- README.rst
readme links are re-ordered to reflect the order of the badges
> add downloads badge
