Ultraplot/UltraPlot

ultraplot/axes/base.py
ultraplot/axes/cartesian.py
ultraplot/axes/shared.py
ultraplot/tests/test_1dplots.py
ultraplot/tests/test_subplots.py

Addresses https://github.com/Ultraplot/ultraplot/issues/11#issuecomment-2590028154
The MPL api changed in v3.6 where get_[x/y]_shared_axes returns an immutable object.

Axis sharing fix

---

.github/workflows/build-ultraplot.yml

Currently, `pytest-mpl `removes the RC file prior to testing, as such we cannot rely on it to test fidelity

Remove pytest mpl from workflow

---

ultraplot/axes/base.py

Addresses #27
Updates `indicate_inset_zoom` to support matplotlib 3.10+ while maintaining backwards compatibility.
- Adds version-specific implementation for matplotlib ≥3.10 using the new `InsetIndicator` class
- Maintains existing implementation for matplotlib <3.10 using rectangle and patches
- Both implementations share the same interface and return format
- For mpl ≥3.10: Uses `InsetIndicator` class which manages both rectangle and connectors in a single object
- For mpl <3.10: Continues to use separate rectangle patch and connector lines
- Implements version checking to automatically select the appropriate implementation

Compatiblity update for mpl 3.10

---

.github/workflows/build-ultraplot.yml
ultraplot/ticker.py

Adding the baseline tests back into ensure future fidelity and make the tests more robust. This would make it easier to track potentially hard to see errors. It would further document future changes in case we wish to deviate from a style in the future.

Add baseline comparison to workflow

---

ultraplot/figure.py

Addresses #43. An issue popped up where the margins are widened when saving a figure without showing the figure first. This can be remedied by forcing a draw prior to calling mpl's `savefig` but feels a bit hacky. Not sure how to do this more cleanly.

Fix margin

---

.github/workflows/build-ultraplot.yml
.github/workflows/main.yml
pyproject.toml

This PR removes the locale matrix elements and adds matplotlib ones.
We cannot yet add MPL 3.10 due to basemap. I have left a comment in the code.
closes #50 
closes #49

test: adjust test matrix to use one locale and add matrix dimension over MPL versions

---

.github/workflows/publish-pypi.yml

Fix PyPI publishing workflow
Updated the workflow to properly handle both release and tag push events:
- For tag pushes: Publishes to TestPyPI first, then PyPI if successful
- For releases: Publishes directly to PyPI, skipping TestPyPI
Fixed conditional logic in the publish-prod job to ensure it runs in both scenarios while maintaining the correct dependency chain.

Second dep on build still being skipped

---

.github/workflows/publish-pypi.yml

This PR fixes the logic in the publish workflow. It uses test pypi for releases and tag pushes, but only pushes releases to pypi.

fix: correct chain of logic for publish workflow

---

.github/workflows/build-ultraplot.yml
.github/workflows/main.yml
.github/workflows/publish-pypi.yml
.gitignore
pyproject.toml
ultraplot/__init__.py

I am copying over the configs from conda-forge-metadata which has a working publish action: https://github.com/conda-forge/conda-forge-metadata/blob/main/.github/workflows/pypi.yml
Hopefully this finally fixes things. 
Right now, setuptools scm is not computing the version from the tag correctly.

fix: get pypi publish working

---

ultraplot/axes/plot.py
ultraplot/tests/test_constructor.py

Ran into this edge when trying to fix the deprecation warnings

add case where cycler is already a cycle

---

.github/workflows/publish-pypi.yml

GHA only allows one workflow run to be queued behind a running one when it does not cancel in progress jobs. By add the SHA to the concurrency group, we allow for PRs to run the pypi build for testing while also allowing tags / releases on main to not be canceled.

fix: make sure PRs do not mess with releases

---

.github/workflows/build-docs.yml
.github/workflows/main.yml
.github/workflows/publish-pypi.yml
pyproject.toml

This PR removes duplicated code in the pypi workflow.
closes #68

feat: deduplicate pypi publish workflow

---

ultraplot/axes/plot.py
ultraplot/tests/test_1dplots.py

use norm explicitly

---

.github/workflows/publish-pypi.yml

The job currently fails as (I believe) the dist path needs to be set similar to how it is done on the test server upload

added path explicitly on publish

---

.github/workflows/publish-pypi.yml

I missed one of the race conditions.

fix: remove race condition for pushes of tags

---

ultraplot/demos.py

Fix demo function not extracting colormaps

---

ultraplot/axes/plot.py
ultraplot/tests/test_1dplots.py

This PR makes the logic for `pcolormesh` specific to `QuadMesh` which is the object returned by `pcolormesh` and is more specific than a `Collection`. 
This ensures that labels are added correctly again when using a heatmap
```python
import ultraplot as plt, numpy as np
x = np.random.rand(10, 10)
fig, ax = plt.subplots(figsize=(5, 5))
ax.heatmap(x, labels=True)
fig.show()
```

Fixes heatmap not showing labels.

---

ultraplot/constructor.py
ultraplot/tests/test_constructor.py

#98 Addresses an issue where explicit key word is given or not. By default the first argument is assumed to be the color spec but that does not have to be the case.

filter out property if not set

---

.github/workflows/build-docs.yml

Should address errors like:
>/home/docs/checkouts/readthedocs.org/user_builds/ultraplot/conda/latest/lib/python3.12/site-packages/cartopy/mpl/gridliner.py:751: UserWarning: Glyph 8242 (\N{PRIME}) missing from font(s) TeX Gyre Heros.
artist.update_bbox_position_size(renderer)

Add texgyre to docs

---

.github/workflows/main-no-changes.yml
.github/workflows/main.yml

This PR will streamline the runs. When updating the docs, the src does not have to be built unless the src was changed.

prod: only build ultraplot when ultraplot src changes

---

ultraplot/axes/base.py
ultraplot/tests/test_2dplots.py

Addresses #105 
When `extend != 'neither'` the additional `update_ticks` is creating ghosting on the ticks. I am not sure why this happened but the `update_ticks` command is overridden by Ultraplot but deprecated by mpl. Removing the function outright breaks code elsewhere that I currently do not fully understand. I would be more in favor of removing this additional function but for now we can fix this by removing this additional call. Unittest is added to safe guard against future changes.

Fix colorbar ticks

---

ultraplot/axes/base.py
ultraplot/tests/test_legend.py

Bug: `kwargs` just has popped out key, and thus, `kwargs[key]` won't work.  It raises KeyError when the value is a string (e.g.,`columnspacing='1em'`)

bugfix for Axes.legend when certain keywords are set to str

---

docs/projections.py
ultraplot/axes/geo.py
ultraplot/tests/test_geographic.py

This PR addresses #125. It introduces a test that tests specifically three use cases.
It modifies the code to allow for showing ticks in geoaxis. Currently, the tickers are completely controlled through the backend with small modifications to ensure high quality plots. This PR makes it to add ticks. It does this by manually adding a ticker when new keywords `lontick` or `lattick` is given which can take a bool or numeric as an input. When set to `None` the option is effectively ignored.
The defaults should generate a sensible plot with lat and long lines, but without ticks. Then it specifically tests whether leaving the ticks on on one axis does not hamper the other axes.
Edit the parameters added would create a 2^4 test plots in terms of the combinations; I opted for specific tests that …

Allow ticks for geoaxes

---

.github/workflows/archive-pytest-results.yml

@cvanelteren this should fix the latest error. A few other comments
1. The `head_branch` is not the merge branch and so it won't have the PR number in it. It appears that for this event the `pull_request` attribute is empty so we'll need to parse the PR by searching the API if we want the number.
2. We need to set the permissions for tokens to null for security reasons. We are checking out untrusted code in the context of the upstream repo.

fix: checkout from correct fork

---

ultraplot/tests/conftest.py
ultraplot/tests/test_1dplots.py
ultraplot/tests/test_2dplots.py
ultraplot/tests/test_axes.py
ultraplot/tests/test_colorbar.py
ultraplot/tests/test_format.py
ultraplot/tests/test_geographic.py
ultraplot/tests/test_imshow.py
ultraplot/tests/test_integration.py
ultraplot/tests/test_legend.py
ultraplot/tests/test_projections.py
ultraplot/tests/test_statistical_plotting.py

This PR sets the seed prior to running any test. This prevents ordering effect if we refactor the tests down the line and ensures that each test is run from the same seed.
Note this will crash all the current baselines but this is fine.

Set seed prior to test to ensure fidelity

---

ultraplot/tests/conftest.py

This PR moves the filter inside a pytest function such that it suppresses unrecognized rc parameters that are native to ultraplot but not matplotlib

Move warning inside pytest config

---

ultraplot/axes/base.py
ultraplot/tests/test_colorbar.py

make cbar labelloc possible for all direction

---

environment.yml

Current workflows are failing due to a missing dep for pandas -- not sure why.  Temporarily adding this such that the workflows can run.

Add pyarrow to rm pandas error

---

docs/_static/custom.css

Moves the figures to center align rather than align left. It also fills the horizontal space  to make the plots bigger and more appealing.

Center figures in docs

---

ultraplot/axes/cartesian.py
ultraplot/figure.py
ultraplot/tests/test_axes.py

Fixes #176 
<details> </summary> code </summary> 
```python
import ultraplot as uplt, numpy as np
layout = [
[1, 2, 0],
[1, 2, 5],
[3, 4, 5],
[3, 4, 0],
]
fig, ax = uplt.subplots(layout)
ax.format(
xticklabelloc="t",
yticklabelloc="r",
)
layout = [
[1, 0, 2],
[0, 3, 0],
[4, 0, 5],
]
fig, ax = uplt.subplots(layout)
ax.format(
xticklabelloc="t",
yticklabelloc="r",
)
uplt.show(block=True)
```
</details>
will now be correct:

Ensure that shared labels are consistently updated.

---

ultraplot/axes/base.py
ultraplot/internals/rcsetup.py
ultraplot/tests/test_colorbar.py

The community indicated (@ToryDeng) that colorbar label placing may need some TLC. We recently introduced placing colorbar labels along the outside of the colorbar. This may cause unnecessary post processing as currently the placingo f the labels is not stylized. This PR adds sensible label placement for colorbars. It adds a new keyword `labelrotation` which is set to default to "auto" or can be set to any arbitrary number; please note the the alignment is then null and void. 
Furthermore, it adds the keyword `outline` which allows for turning on and off the outline frame of the colorbar.
Addresses #181 
@TorryDeng do you want to include an rc param for the frame or is this sufficient?

sensible defaults and unittest

---

docs/conf.py
docs/index.rst
docs/networks.py
environment.yml
ultraplot/axes/base.py
ultraplot/axes/plot.py
ultraplot/internals/rcsetup.py
ultraplot/tests/test_1dplots.py
ultraplot/tests/test_axes.py
ultraplot/tests/test_plot.py

Networks are the base of many disciplines, and visualizing them is an important part of understanding how "intuitively" graphs differ from one another. A pet peeve of mine is that network plotting is verbose or too opaque with poor chosen defaults, preventing clear communication of the intended purpose: highlighting connections.
This PR presents an interface for plotting networkx graphs. It provides sensible defaults and makes beautiful default plots while still allowing access to changes when needed. Networkx has grown to be the often de facto standard for visualizing and base analysis of small to medium networks in python. It has a nice drawing interface that is unfortunately a bit verbose. By drawing on the power of networkx, we can enhance the plotting experience by providing a tight …

Add network plotting to UltraPlot

---

ultraplot/axes/plot.py
ultraplot/internals/rcsetup.py
ultraplot/tests/test_plot.py

Fix and issue where categorical data is used for quiver plots. Fixes #197 
```python
import ultraplot as uplt, numpy as np
X = np.array([0, 1, 2])
Y = np.array([0, 1, 2])
U = np.array([1, 1, 0])
V = np.array([0, 1, 1])
import matplotlib.colors
colors = ["red", "green", "blue"]  
colors = [matplotlib.colors.to_rgb(color) for color in colors]
fig, ax = uplt.subplots()
q = ax.quiver(X, Y, U, V, colors=colors, infer_rgb=True)
ax.set_aspect("equal")
uplt.show()
```

Discrete colors for quiver

---

ultraplot/axes/plot.py
ultraplot/internals/rcsetup.py
ultraplot/tests/test_plot.py

This PR introduces a new rc parameters `formatter.log` which is set to `False` by default. When set to true it automatically applies a `log` scale for x, y or both depending on the plotting function used (`semilogx, semilogy`, and `loglog` respectively).  
Addresses #199

override logx/y/log with updated docstring

---

docs/networks.py
ultraplot/axes/plot.py

Networkx requires full path names for drawing functions. This PR fixes minor linking issues on the docs page and in the api for networkx functions.

Fix network linking in docs and api refs

---

ultraplot/gridspec.py

I'm personally a strong proponent of calling plot methods directly on a series of axes. With that in mind, I believe we should remove this method, as I intend to continue supporting that approach. That said, I'm open to discussion if there's an important consideration I'm overlooking. One of UltraPlot’s strengths is its ability to simplify the management of subplot properties while still allowing fine-grained control. For that reason, I suggest we remove this statement.

rm dep warning

---

.github/workflows/build-ultraplot.yml

This PR makes the test suite about 6 minutes faster by running the image comparison tests in parallel with the main test suite.

perf: run comparison tests at the same time as the main tests

---

ultraplot/axes/geo.py
ultraplot/tests/test_geographic.py

This PR addresses #217. The recent added feature of sharing GeoAxes did not test when `PlotAxes` methods are called on `GeoAxes`. We don't have to apply the GeoSharing there; alternatively we could add the private function to the CartesianPlots. In this PR we just skip these axes.

Skip sharing logic when colorbar is added to GeoPlots.

---

ultraplot/axes/plot.py
ultraplot/tests/test_geographic.py

Addresses #221. This feature was inadvertently removed by addressing a bug that allowed for parsing tricontour plots.

Restore redirection for tricontourf for GeoPlotting

---

ultraplot/axes/geo.py
ultraplot/figure.py
ultraplot/tests/test_axes.py
ultraplot/tests/test_format.py
ultraplot/tests/test_geographic.py

The colorbar (apparently) fundamentally changes the gridspec in a non-trivial way, see #234. This causes an issue with the introduced `GeoAxes` sharing feature where the borders were determined based on the position in the gridpec. We can sidestep this issue by using the gridspec of the figure to reconstruct the position.
Current implementation now produces

Hotfix get_border_axes

---

ultraplot/axes/base.py
ultraplot/tests/test_geographic.py

Hotfix GeoAxes indicate zoom. This PR ensures that the zorder is above that of the axes. Addresses #245.

Hotfix GeoAxes indicate zoom. 

---

ultraplot/axes/base.py
ultraplot/axes/geo.py
ultraplot/figure.py
ultraplot/tests/test_geographic.py

Addresses #252 
```python
import ultraplot as uplt, numpy as np, pandas as pd
import numpy as np
import matplotlib.patheffects as pe
fig, ax = uplt.subplots(proj="cyl")
ax.format(
latlabels="l",
lonlabels="b",
)
uplt.show(block=1)
```

GeoTicks not responsive

---

ultraplot/tests/test_1dplots.py
ultraplot/tests/test_format.py
ultraplot/tests/test_geographic.py
ultraplot/tests/test_plot.py

Pytest has a stricter requirement on tests returning objects without being marked as such. This fixes the tests that do this.

Update return requirements pytest 8.4.0

---

.zenodo.json
CITATON.cff
README.rst

This PR formally introduces citation metadata for the UltraPlot project.
UltraPlot is a continuation of the original [ProPlot](https://github.com/lukelbd/proplot) library, which has not seen active development since 2022. While ProPlot laid the foundation for many of the ideas in UltraPlot, this project has been significantly restructured, modernized, and extended, and is being actively maintained.
To acknowledge this transition and to support reproducible and citable scientific software, we now include:
- A `CITATION.cff` file for automatic citation support on GitHub and with Zotero.
- A `.zenodo.json` file for future DOI integration via Zenodo.
- A BibTeX citation in the README for easy copy-paste into academic manuscripts.
We are committed to maintaining this project as a reliable and …

Add citation metadata (CITATION.cff, .zenodo.json) to support scholarly use

---

ultraplot/axes/geo.py
ultraplot/tests/test_geographic.py
ultraplot/ticker.py

Addresses #292 where DMS is not set for some axes that should have it set.

Fix DMS not set on some projections

---

ultraplot/colors.py
ultraplot/tests/test_colormap.py

A secondary issue came up in #294 where a callable is not properly inverse. 
This PR fixes a bug in the reversal of colormap segment data where callable segments were incorrectly captured due to Python’s late binding behavior in closures. Specifically, lambdas inside the dictionary comprehension referenced the loop variable data, which caused all callables to use the last data value. This is resolved by binding data as a default argument in the lambda. Explicit segment lists are unaffected and still reversed correctly.

fix late binding and proper reversal for funcs

---

ultraplot/axes/base.py
ultraplot/legend.py
ultraplot/tests/test_legend.py

An issue popped up in #309  where if locations are changed for legends they are not synced with `_legend_dict`. This PR fixes this by override the `set_loc` function of legend. 
Why was this an issue? UltraPlot allows for updating the styling of legends when a legend already exists on at that location. Since the internal reference is used, a sync issue appears if for whatever reason the legend is moved.

Sync `_legend_dict` on legend location change

---

ultraplot/internals/inputs.py
ultraplot/tests/test_inputs.py
ultraplot/tests/test_plot.py

This PR will attempt to parse the data inputs as a `dtype=object` if the input has different dimensions as was the case in #317. This would allow for more flexible parsing in violin and boxplots.

Handle non homogeneous arrays 

---

ultraplot/tests/test_plot.py

I think the current failure on main is because one of the violin plots uses `np.random` without a fixed seed.

Fix inhomogeneous violin test

---

docs/subplots.py
ultraplot/axes/base.py

This PR updates the documentation in `ultraplot/docs/subplots.py` to clarify the functionality of the `abc` parameter for formatting subplot labels and its usage in the `format` command. The changes aim to provide a comprehensive explanation of how users can utilize the `abc` parameter across different contexts.
- Revised the wording to explain that the `abc` parameter can:
- Be used as a template to format subplot labels, such as "A.", which assigns alphabetic labels based on the axis number.
- Accept a list, where the elements of the list are used as labels for the subplots.
- Updated the documentation to highlight that the `abc` parameter can also be enabled via the `format` command by setting `abc=True`.
The previous documentation mentioned "a-b-c" labels but did not clearly describe …

Update Documentation for `abc` Parameter in Subplots and Format Command

---

docs/api.rst
docs/subplots.py

Addresses issue where some links are not found.
Fixes #331

Add members to api

---

ultraplot/tests/test_imshow.py
ultraplot/tests/test_subplots.py

Small clean up on the tests that still have `fig.show` or `uplt.show`

rm show from tests

---

ultraplot/axes/cartesian.py
ultraplot/tests/test_axes.py

Closes #345 
This PR sanitizes the labelpad/size params or x and y axis.
Changes:
- explicitly sanitize the `ticklen, ticklabelpad, tickwidth, labelsize, ticklabelsize` within the loop of Cartesian axes.
- Add unittest for setting labelpad and or size

Sanitize pad and len formatters on Cartesian Axes

---

ultraplot/internals/labels.py
ultraplot/tests/test_format.py

Closes #352 
The `_transfer_label(src, dest)` function is responsible for transferring text and font properties from a source text object (`src`) to a destination text object (`dest`). Currently, the function sets all font properties of `dest` to match those of `src` every time it is called:
```python
font_properties = src.get_font_properties()
dest.set_fontproperties(font_properties)
```
This approach causes an issue when `_transfer_label` is called multiple times on the same `dest` object. Any customizations or updates made to `dest`'s font properties after the first transfer are lost, as they are overwritten by `src`'s properties on subsequent calls.
1. `_transfer_label(src, dest)` is called — `dest` now has `src`'s font properties.
2. The user or another function updates `dest`'s font …

Fix order of label transfer

---

ultraplot/axes/geo.py
ultraplot/gridspec.py
ultraplot/tests/test_geographic.py
ultraplot/tests/test_subplots.py

Closes #356 and #358
This PR addresses two critical bugs introduced after v1.0: one causing incorrect indexing in `SubplotGrid`, and another causing sequential `format` calls on `GeoAxes` to override each other.
While this work is part of the larger effort in #349, this fix is being prioritized to resolve significant issues for users on the latest version.
-   **The Issue:** Slicing a `SubplotGrid` using 2D grid coordinates (e.g., `axs[:, 0]`) resulted in an incorrect selection of axes.
-   **The Fix:** The `SubplotGrid.__getitem__` method in `ultraplot/gridspec.py` has been reverted to the robust implementation from v1.0, which correctly handles array-like indexing.
-   **The Issue:** When applying formatting to a `GeoAxes` object in sequence, the second call would override the first. …

 Fix: Corrects `SubplotGrid` indexing and sequential `GeoAxes` formatting
